In [2]:
import pandas as pd

In [ ]:
produtos_df = pd.read_csv('Produtos.csv', sep=';') # sep seria o separador das informações para visualizar melhor
#print(produtos_df) # nao precisa print pra visualizar
produtos_df

,Nome da Marca,Tipo,Custo Unitario,Preco Unitario,ID Produto,Categoria
0,Contoso,Econômico,"10,69","20,96",873,Acessório para Computador
1,Contoso,Econômico,"6,63",13,879,Acessório para Computador
2,Contoso,Econômico,"6,63",13,880,Acessório para Computador
3,Contoso,Econômico,"6,63",13,881,Acessório para Computador
4,Contoso,Econômico,"6,63",13,882,Acessório para Computador
...,...,...,...,...,...,...
1685,Southridge Video,Regular,"82,77","179,99",1602,Filme DVD
1686,Southridge Video,Regular,"73,57","159,99",1606,Filme DVD
1687,Southridge Video,Regular,"82,77","179,99",1607,Filme DVD
1688,Southridge Video,Regular,"73,57","159,99",1611,Filme DVD
1689,Southridge Video,Regular,"82,77","179,99",1612,Filme DVD

In [6]:
vendas_df = pd.read_csv('Vendas2017.csv', sep=';')
vendas_df

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1
...,...,...,...,...,...,...,...,...,...,...
980637,980638,31/12/2017,31/12/2017,0,194,2490,4,10353,120,0
980638,980639,31/12/2017,06/01/2018,6,32,2488,4,31750,120,0
980639,980640,31/12/2017,03/01/2018,3,210,2511,10,12003,80,0
980640,980641,31/12/2017,31/12/2017,0,53,436,4,25550,39,0
980641,980642,31/12/2017,31/12/2017,0,309,2510,10,28707,80,0

In [ ]:
vendas_df['ID Cliente']# trazendo apenas colunas

0          6825
1         18469
2         19730
3         29326
4         22617
          ...
980637    10353
980638    31750
980639    12003
980640    25550
980641    28707
Name: ID Cliente, Length: 980642, dtype: int64

In [ ]:
vendas_df[:20]
# Assim como lista em python o data frame usa o indece : para ate

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1
5,6,01/01/2017,01/01/2017,0,157,1046,2,7910,4,1
6,7,01/01/2017,09/01/2017,8,10,1261,2,11720,4,1
7,8,01/01/2017,05/01/2017,4,303,958,10,26558,4,1
8,9,01/01/2017,05/01/2017,4,213,1509,10,32396,8,1
9,10,01/01/2017,01/01/2017,0,199,1318,2,31290,8,1
10,11,01/01/2017,08/01/2017,7,257,900,5,30488,6,1
11,12,01/01/2017,04/01/2017,3,304,597,10,18561,4,1
12,13,01/01/2017,01/01/2017,0,13,167,2,25632,4,1
13,14,01/01/2017,01/01/2017,0,199,632,2,30401,8,1
14,15,01/01/2017,01/01/2017,0,207,1602,10,36839,8,1
15,16,01/01/2017,06/01/2017,5,309,599,10,27645,16,1
16,17,01/01/2017,01/01/2017,0,225,1383,10,7991,4,1
17,18,01/01/2017,09/01/2017,8,204,882,10,35762,4,1
18,19,01/01/2017,02/01/2017,1,211,1402,10,24240,8,1
19,20,01/01/2017,02/01/2017,1,208,1296,10,13399,8,1

In [11]:
vendas_df[['Numero da Venda','Data da Venda','ID Loja']]

        Numero da Venda Data da Venda  ID Loja
0                     1    01/01/2017       86
1                     2    01/01/2017      308
2                     3    01/01/2017      294
3                     4    01/01/2017      251
4                     5    01/01/2017       94
...                 ...           ...      ...
980637           980638    31/12/2017      194
980638           980639    31/12/2017       32
980639           980640    31/12/2017      210
980640           980641    31/12/2017       53
980641           980642    31/12/2017      309

[980642 rows x 3 columns]

In [12]:
vendas_df['ID Produto'][25]

np.int64(348)

In [14]:
vendas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980642 entries, 0 to 980641
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  str
 2   Data do Envio         980642 non-null  str
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
dtypes: int64(8), str(2)
memory usage: 74.8 MB

In [7]:
clientes_df = pd.read_csv('Clientes.csv', sep=';')
clientes_df

,ID Cliente,Primeiro Nome,Sobrenome,E-mail,Genero,Numero de Filhos,Data de Nascimento,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,Garnet,Lanfranchi,glanfranchi0@mayoclinic.com,Feminino,2,12/05/1995,NaN,NaN,NaN,NaN
1,2,Lurette,Roseblade,lroseblade1@bigcartel.com,Feminino,2,30/06/1943,NaN,NaN,NaN,NaN
2,3,Glenden,Ishchenko,gishchenko2@moonfruit.com,Masculino,5,09/04/1989,NaN,NaN,NaN,NaN
3,4,Baron,Jedrzejewsky,bjedrzejewsky3@e-recht24.de,Masculino,4,17/11/1998,NaN,NaN,NaN,NaN
4,5,Sheree,Bredbury,sbredbury4@sitemeter.com,Feminino,5,08/09/1975,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
39499,39500,Brandy,Malhotra,brandy0@adventure-works.com,Masculino,3,27/07/1980,NaN,NaN,NaN,NaN
39500,39501,Alicia,Raje,alicia12@adventure-works.com,Feminino,5,10/05/2001,NaN,NaN,NaN,NaN
39501,39502,Connie,Rai,connie4@adventure-works.com,Feminino,0,13/02/1997,NaN,NaN,NaN,NaN
39502,39503,Shawn,Raji,shawn23@adventure-works.com,Masculino,1,29/03/2001,NaN,NaN,NaN,NaN
39503,39504,Lindsey,Sharma,lindsey10@adventure-works.com,Feminino,0,19/11/1961,NaN,NaN,NaN,NaN